/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.CardLayout;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;

/**
 *
 * @author USER
 */
public class PilihGambarButtonFullscreen extends javax.swing.JFrame {

    /**
     * Creates new form PilihGambarButton
     */
    public PilihGambarButtonFullscreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnPanel = new javax.swing.JPanel();
        BtBjm = new javax.swing.JButton();
        BtHandil = new javax.swing.JButton();
        BtBjb = new javax.swing.JButton();
        BtKeluar = new javax.swing.JButton();
        ImagePanel = new javax.swing.JPanel();
        ImgBanjarbaru = new javax.swing.JLabel();
        ImgRantau = new javax.swing.JLabel();
        ImgKandangan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        BtnPanel.setBackground(new java.awt.Color(153, 255, 153));

        BtBjm.setText("Banjarbaru");
        BtBjm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtBjmActionPerformed(evt);
            }
        });
        BtnPanel.add(BtBjm);

        BtHandil.setText("Rantau");
        BtHandil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtHandilActionPerformed(evt);
            }
        });
        BtnPanel.add(BtHandil);

        BtBjb.setText("Kandangan");
        BtBjb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtBjbActionPerformed(evt);
            }
        });
        BtnPanel.add(BtBjb);

        BtKeluar.setText("Keluar");
        BtKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtKeluarActionPerformed(evt);
            }
        });
        BtnPanel.add(BtKeluar);

        getContentPane().add(BtnPanel, java.awt.BorderLayout.PAGE_START);

        ImagePanel.setBackground(new java.awt.Color(51, 255, 255));
        ImagePanel.setLayout(new java.awt.CardLayout());

        ImgBanjarbaru.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImgBanjarbaru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/banjarbaru.jpg"))); // NOI18N
        ImagePanel.add(ImgBanjarbaru, "0");

        ImgRantau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/rantau.jpg"))); // NOI18N
        ImagePanel.add(ImgRantau, "1");

        ImgKandangan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/kandangan.JPG"))); // NOI18N
        ImagePanel.add(ImgKandangan, "2");

        getContentPane().add(ImagePanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtBjmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtBjmActionPerformed
        CardLayout cl = (CardLayout)(ImagePanel.getLayout());
        cl.show(ImagePanel, "0");
    }//GEN-LAST:event_BtBjmActionPerformed

    private void BtHandilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtHandilActionPerformed
        CardLayout cl = (CardLayout)(ImagePanel.getLayout());
        cl.show(ImagePanel, "1");
    }//GEN-LAST:event_BtHandilActionPerformed

    private void BtBjbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtBjbActionPerformed
        CardLayout cl = (CardLayout)(ImagePanel.getLayout());
        cl.show(ImagePanel, "2");
    }//GEN-LAST:event_BtBjbActionPerformed

    private void BtKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtKeluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BtKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButtonFullscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButtonFullscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButtonFullscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PilihGambarButtonFullscreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PilihGambarButtonFullscreen fullFrame = new PilihGambarButtonFullscreen();
                
                GraphicsDevice device =
                        GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
                device.setFullScreenWindow(fullFrame);
                
                fullFrame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtBjb;
    private javax.swing.JButton BtBjm;
    private javax.swing.JButton BtHandil;
    private javax.swing.JButton BtKeluar;
    private javax.swing.JPanel BtnPanel;
    private javax.swing.JPanel ImagePanel;
    private javax.swing.JLabel ImgBanjarbaru;
    private javax.swing.JLabel ImgKandangan;
    private javax.swing.JLabel ImgRantau;
    // End of variables declaration//GEN-END:variables
}
